# Generated by Django 3.2.16 on 2022-11-10 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('price', models.CharField(max_length=100)),
                ('total', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('order_date', models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 10, 23, 20, 31, 848556))),
                ('user_id', models.IntegerField(blank=True)),
                ('delivery', models.BooleanField(default=False)),
            ],
        ),
    ]
